# Generated by Django 4.0.5 on 2022-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('warehouse', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
